apiVersion: v1
kind: Pod
metadata:
  name: terminal
spec:
  containers:
  - name: terminal
    image: wokenqingtian/kubernetes-rails-example:latest
    command: ['sleep']
    args: ['infinity']
    env:
      - name: RAILS_PRODUCTION_KEY
        valueFrom:
          secretKeyRef:
            name: k-secrets
            key: rails-master-key
    envFrom:
    - configMapRef:
        name: kubernetes-rails-example-env